repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    files: \.py$
    args: [--max-line-length=120, --extend-ignore=E203,W503]
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    files: \.py$
    args: [--max-line-length=120, --disable=missing-docstring,too-many-locals,too-many-arguments]
  - id: pycodestyle
    name: pycodestyle
    entry: pycodestyle
    language: python
    files: \.py$
    args: [--max-line-length=120, --ignore=E203,W503]
  - id: pydocstyle
    name: pydocstyle
    entry: pydocstyle
    language: python
    files: \.py$
    args: [--convention=google]
  - id: bandit
    name: bandit
    entry: bandit
    language: python
    files: \.py$
    args: [-r, --skip=B101]
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    files: \.py$
    args: [--strict, --ignore-missing-imports]